name: Brain Tumour Detection ML Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt

    - name: Set up Kaggle credentials
      run: |
        mkdir -p ~/.kaggle
        echo "${{ secrets.KAGGLE_JSON }}" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json

    - name: Download dataset from Kaggle
      run: |
        . venv/bin/activate
        pip install -q kaggle
        kaggle datasets download -d "sartajbhuvaji/brain-tumor-classification-mri" -p "./data"

    - name: Unzip dataset
      run: |
        unzip ./data/brain-tumor-classification-mri.zip -d ./data

    - name: Execute classification notebook
      run: |
        . venv/bin/activate
        jupyter nbconvert --to notebook --execute classification.ipynb --output classification_output.ipynb

    - name: Execute resUnet notebook
      run: |
        . venv/bin/activate
        jupyter nbconvert --to notebook --execute resUnet.ipynb --output resUnet_output.ipynb

    - name: Run tests
      run: |
        . venv/bin/activate
        pytest
